import gnupg
import os 

# The code will generate the GPG key pair and save it in the GPG Directory
# The GPG directory is set in the default location 
# The GPG should be installed in the system

gpg = gnupg.GPG(gnupghome=os.path.expanduser('~/.gnupg'))
gpg.encoding = 'utf-8'

input_data = gpg.gen_key_input(
    key_type='RSA',
    key_length=2048,
    name_real='Test Key',
    name_comment='Generated by Patch Management test script',
    expire_date='2y')

key = gpg.gen_key(input_data)

print(key)